name: Android CI

on: [push,pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  jvm:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 1.8

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      #        - name: Make gradlew executable
      #          run: chmod +x ./gradlew
      - name: Build with Gradle
        run: sudo ./gradlew build
  #       - name: Test
  #         run: sudo ./gradlew build

#   android:
#     runs-on: macos-latest

#     strategy:
#       fail-fast: false
#       matrix:
#         api-level:
#           - 21
#           - 24
#           - 26
#           - 29

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Validate Gradle Wrapper
#         uses: gradle/wrapper-validation-action@v1

#       - name: Run Tests
#         uses: reactivecircus/android-emulator-runner@v2
#         with:
#           api-level: ${{ matrix.api-level }}
#           script: ./gradlew connectedCheck
#         env:
#           API_LEVEL: ${{ matrix.api-level }}

#   robovm:
#     runs-on: macos-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Validate Gradle Wrapper
#         uses: gradle/wrapper-validation-action@v1

#       - name: Run Tests
#         run: ./gradlew retrofit:robovm-test:robovmTest

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
#     - name: Run Gradlew.bat
#       run: sudo gradlew.bat build
#     - name: Build with Gradle
#       run: ./gradlew build
